### ISSUE TITLE
API key is now mandatory

### ISSUE THREAD

**Issue by aseriy** [cmfcmf/OpenWeatherMap-PHP-Api#57]
According to http://openweathermap.org/appid, the API key is now required to make the API calls whether you have a free or paid for account. This means that the api key must be passed to each getWeather() since the default is NULL.
It's not a bug at this point since there is a way around it by explicitly passing the api key to every call, but it does break the Examples. It's probably a good idea to add the addition parameter to the OpenWeatherMap() constructor to set the default api key in the class and then use it as the default in all the other methods, unless overridden.

**Comment by aseriy** [comment]
I modified the code to implement this. BTW, I'm wondering what type of subscription you need to run the Examples. I was able to run the CurrentWeather and WeatherForecast with the FREE account although I would get "HTTP/1.1 401 Unauthorized" if I wasn't passing the APPID. The last example, WeatherHistory would return a 401 with the free account. I checked http://openweathermap.org/price and it looks like you need a paid for subscription to get the historic data.
I'm glad to check in my changes and do a pull request if you're ok with you. Please let me know the details. Thanks.

**Comment by cmfcmf** [comment]
Hi @aseriy,

thank you for your research. When I initially created the api, all services, including weather history, were free to use even without APPID. 
I admit it makes sense to add a setAppId / setApiKey method and then use the given key whenever no key is explicitly provided in `getWeather` etc. calls. OpenWeatherMap both uses the APPID and Api Key terms - I'd prefer Api Key, because that term is more common for apis.
I'd be thankful if you created a pull request with your changes. Also feel free to update the examples with a note about the api key requirement.

When I find time for a version 3 of the api, I'll then remove the appid parameters from the `getWeather` etc. calls as well as the `setApiKey` method and probably require a parameter inside the constructor.

**Comment by aseriy** [comment]
Sure, I'm happy to create a pull request. Which branch should it be on?

**Comment by aseriy** [comment]
Hi @cmfcmf,
I address your comments on the Pull request. Please let me know if you have any additional comments.
Thanks

**Comment by cmfcmf** [comment]
Fixed by #63.

**Comment by aseriy** [comment]
Hi @cmfcmf,
I would like to share some thoughts about this project that might be of interest to you. I was wondering if we could connect via email, phone or Skype. Please feel free to email me at aseriy@us.ibm.com at your convenience, if you're interested.
Kind regards,
Alex
